# version: '3.8'
# services:
#   dev-database:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     container_name:  dev-database
#     environment:
#        MSSQL_SA_PASSWORD : '123'
#        MSSQL_PID: 'Express'
#        ports: '1433'  
#     networks:
#       - nestjs-networks
# networks:
#   nestjs-networks:




  # Explicitly specify a supported version 




services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6380"
    volumes:
      - ./data:/data
    


  # pssql:
  #   image: postgress:latest
  #   container_name: postgressSQL
  #   environment:
  #     - POSTGRESS_USER=postgress  # Use a secret for password
  #     - POSTGRESS_PASSWORD=ABC123123
  #     - database=testdb
  #   ports:
  #     - 5434:5432
  #   networks:
  #     - nestjs-network
    